(define (problem cook-1)
	(:domain cook) 
	(:objects stove serve bottle bowl strawberry reserve) 
	(:init (Stove stove) 
			(Serve serve) 
			(Pourable bottle) 
			
			(Stackable bottle stove) 
			(Stackable bottle serve) 
			(Stackable bowl serve) 
			(Stackable bowl stove) 
			(Stackable bottle reserve) 
			(Stackable bowl reserve) 
			
			(Fireproof bowl)

			(On strawberry bottle) 
			(On bottle reserve) 
			(On bowl reserve) 
			(Graspable bottle) 
			(Graspable bowl)

			(HandEmpty) 
            )
	(:goal (and (Served strawberry)))
    ;(:goal (and (Holding bottle)))
)
